version: "3.7"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
#    command: ["redis-server", "--appendonly", "yes", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-data:/data
#      - /storage-data/redis.conf:/usr/local/etc/redis/redis.conf

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=Zu0r4#!1
    ports:
      - 9081:8081
    depends_on:
      - redis

#if you want to expose this environment externally uncomment lines bellow
#  ngrok:
#    image: wernight/ngrok:latest
#    ports:
#      - 4042:4040
#    environment:
#        NGROK_PROTOCOL: http
#        NGROK_PORT: redis-commander:8081
#        NGROK_AUTH: 'your-ngrok-key-here'
#        NGROK_DEBUG: 'true'

volumes:
  redis-data:
